### ISSUE TITLE
GPG problems on Cygwin?

### ISSUE THREAD

**Issue by ylluminarious** [wayneeseguin/rvm#3213] opened 2014-12-19 17:51 UTC
I have installed GPG and it seems to work from my cygwin zsh terminal, however I get an error each time I attempt to install RVM.

Here is the output of `gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3`:
```
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

Then when I attempt to install with `\curl -sSL https://get.rvm.io | bash -s stable`, I get:
```
Downloading https://github.com/wayneeseguin/rvm/archive/1.26.4.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.4/1.26.4.tar.gz.asc
gpg: can't open `/home/username/.rvm/archives/rvm-1.26.4.tgz.asc': No such file or directory
gpg: verify signatures failed: No such file or directory
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/username/.rvm/archives/rvm-1.26.4.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.4/1.26.4.tar.gz.asc'!
try downloading the signatures:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
```

This file does appear to exist, but I keep hitting walls. Is there a flag that I can pass the rvm installation script to bypass this security check?

**Comment by mpapis** [comment] 2015-01-04 17:57
closing as there was no feedback in two weeks, let me know if you can provide more details and I will reopen

**Comment by sharwell** [comment] 2015-01-07 00:31
I received this message today. I believe the issue is the script is using `gpg2` instead of `gpg`, but Cygwin only provides the latter.

```
sam@P ~
$ which gpg
/usr/bin/gpg

sam@P ~
$ which gpg2
/cygdrive/c/Program Files (x86)/GNU/GnuPG/pub/gpg2
```

**Comment by mpapis** [comment] 2015-01-07 00:41
the problem might be with quoting path to `gpg2` - reopening, I will check it

**Comment by mpapis** [comment] 2015-01-07 00:43
and the quoting is done properly, what version of RVM do you use?

**Comment by sharwell** [comment] 2015-01-07 00:46
The GnuPG for Windows build (gpg2 in the above snippet) does not understand Cygwin paths. It's expecting a Windows file system path.

Renaming **C:\Program Files (x86)\GNU\GnuPG** to **C:\Program Files (x86)\GNU\GnuPG-bak** caused the RVM installer to fall back to using `gpg` instead of `gpg2`, which worked (or at least proceeded much farther before hitting an error on my system).

**Comment by mpapis** [comment] 2015-01-07 01:07
it should work after `rvm get head`

**Closed** 2015-01-07 01:06 UTC
Labels: feedback needed

**Comment by sharwell** [comment] 2015-01-07 01:16
I'm not entirely sure what that means. However, I noted the folowing additional items on Cygwin:

1. I had to copy **setup-x86.exe** (the Cygwin setup) to **C:\cygwin\bin**.
2. I had to run the Cygwin terminal as an administrator (otherwise the call to **setup-x86.exe** fails with an access denied error).
3. I see several lines saying `rvm_debug: command not found`, but it doesn't seem to be causing problems.

The installer is still running...

**Comment by mpapis** [comment] 2015-01-07 01:19
if the installer continues it's a good sign, please open a new ticket with the other steps you have found that are required

**Comment by alexed1** [comment] 2015-03-31 15:35
I'm having the same problem. installation fails with:

gpg: can't open `/home/alexedhome/.rvm/archives/rvm-1.26.11.tgz.asc'
gpg: verify signatures failed: file open error
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures                          when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the si                         gnatures).


I've verified that I do have the public key downloaded. 

I see that you've added a fix here but I can't run rvm get head because I can't get rvm installed. 

I tried the rename change that worked for Sharwell but it doesn't appear to have had any effect.

Can you provide a little more information on how to move forward here? 

Is it possible to get a version that doesn't require ssl key verification? 

many thanks

**Comment by bezeek** [comment] 2015-04-01 13:55
I'd just like to confirm that this issue still exists today, and offer a synopsis and workaround.

### Environment:

* Windows 7 x64
* Gpg4win
* Cygwin (with gnupg installed from cygwinports.org)

### Steps to reproduce (in a Cygwin Terminal):

0. `$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3`
```
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: DBG: armor-keys-failed (KEY 0x409B6B1796C275462A1703113804BB82D39DC0E3 BEGIN
) ->0
gpg: DBG: armor-keys-failed (KEY 0x409B6B1796C275462A1703113804BB82D39DC0E3 END
) ->0
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

0. `$ curl -sSL https://get.rvm.io | bash -s stable --ruby`
```
Downloading https://github.com/wayneeseguin/rvm/archive/1.26.11.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc
gpg: Signature made Mon, Mar 30, 2015  5:52:13 PM EDT using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/home/USERNAME/.rvm/archives/rvm-1.26.11.tgz'

Installing RVM to /home/USERNAME/.rvm/
```

### Cause:

Due to the presence of Gpg4win, `which gpg2` points to `/cygdrive/PATH/TO/GNU/GnuPG/pub/gpg2.exe`. This binary does not understand Cygwin paths such as `/home/USERNAME/.rvm/archives/rvm-VERSION.tgz.asc`, and therefore fails to locate the file.

### Workaround:

1. Locate and rename `gpg2.exe` as provided by Gpg4win to `gpg2.bak.exe` or whatever you prefer.
2. In a Cygwin Terminal:
  * `which gpg2` should return `which: no gpg2 in (...)`.
  * `which gpg` should return `/usr/bin/gpg` or similar; not a path beginning with `/cygdrive`.
3. Proceed to battle your way through the rvm installation, guided by the official installation instructions and a bit of Google-fu.
4. Reverse the process in step 1, so Gpg4win doesn't bite your head off next time you try to use it.

**Comment by mpapis** [comment] 2015-04-01 14:02
@bezeek can you open a pull request for using `which gpg` if `gpg2` path starts with `/cugdrive`? @havenwood - ping

**Comment by bezeek** [comment] 2015-04-01 14:49
@mpapis: I'm in a bit of a fight with Git about which credentials belong to my personal account, but I'll have that PR up shortly :)
